import type { ComponentType } from "react";
import {
  IconFAbacus,
  IconFAlembic,
  IconFAlarmClock,
  IconFAtomSymbol,
  IconFBarChart,
  IconFBookmark,
  IconFBookmarkTabs,
  IconFBooks,
  IconFBrain,
  IconFCalendar,
  IconFCamera,
  IconFClipboard,
  IconFCompass,
  IconFGlobeShowingAmericas,
  IconFGlobeShowingAsiaAustralia,
  IconFGlobeWithMeridians,
  IconFGraduationCap,
  IconFLaptop,
  IconFLightBulb,
  IconFMagnet,
  IconFMemo,
  IconFMicroscope,
  IconFMusicalNote,
  IconFNotebook,
  IconFNotebookWithDecorativeCover,
  IconFPen,
  IconFPencil,
  IconFSchool,
  IconFSparkles,
  IconFStar,
  IconFTestTube,
  IconFTrophy,
  IconFMapOfJapan,
} from "react-fluentui-emoji/lib/flat";

export type FluentIconProps = { size?: number | string; className?: string; style?: React.CSSProperties };

export const CLASS_ICON_IDS = [
  "books",
  "graduation-cap",
  "notebook",
  "school",
  "notebook-pen",
  "pen",
  "abacus",
  "alembic",
  "microscope",
  "globe",
  "map",
  "compass",
  "light-bulb",
  "brain",
  "atom-symbol",
  "bookmark",
  "laptop",
  "clipboard",
  "pencil",
  "test-tube",
  "bookmark-tabs",
  "sparkles",
  "notebook-decorative",
  "globe-americas",
  "globe-asia",
  "alarm-clock",
  "calendar",
  "bar-chart",
  "memo",
  "magnet",
  "star",
  "trophy",
  "camera",
  "musical-note",
] as const;

export type ClassIconId = (typeof CLASS_ICON_IDS)[number];

export const DEFAULT_CLASS_ICON_ID: ClassIconId = "books";
export const DEFAULT_CLASS_COLOR_HEX = "#3B82F6";

export const CLASS_ICON_MAP: Record<ClassIconId, ComponentType<FluentIconProps>> = {
  "books": IconFBooks,
  "graduation-cap": IconFGraduationCap,
  "notebook": IconFNotebook,
  "school": IconFSchool,
  "notebook-pen": IconFNotebookWithDecorativeCover,
  "pen": IconFPen,
  "abacus": IconFAbacus,
  "alembic": IconFAlembic,
  "microscope": IconFMicroscope,
  "globe": IconFGlobeWithMeridians,
  "map": IconFMapOfJapan,
  "compass": IconFCompass,
  "light-bulb": IconFLightBulb,
  "brain": IconFBrain,
  "atom-symbol": IconFAtomSymbol,
  "bookmark": IconFBookmark,
  "laptop": IconFLaptop,
  "clipboard": IconFClipboard,
  "pencil": IconFPencil,
  "test-tube": IconFTestTube,
  "bookmark-tabs": IconFBookmarkTabs,
  "sparkles": IconFSparkles,
  "notebook-decorative": IconFNotebookWithDecorativeCover,
  "globe-americas": IconFGlobeShowingAmericas,
  "globe-asia": IconFGlobeShowingAsiaAustralia,
  "alarm-clock": IconFAlarmClock,
  "calendar": IconFCalendar,
  "bar-chart": IconFBarChart,
  "memo": IconFMemo,
  "magnet": IconFMagnet,
  "star": IconFStar,
  "trophy": IconFTrophy,
  "camera": IconFCamera,
  "musical-note": IconFMusicalNote,
};

/** Returns the Fluent Emoji component for the given icon ID. Unknown IDs (e.g. legacy Lucide IDs) fall back to default. */
export function getClassIcon(iconId: string | null | undefined): ComponentType<FluentIconProps> | null {
  if (!iconId || !CLASS_ICON_IDS.includes(iconId as ClassIconId)) {
    return CLASS_ICON_MAP[DEFAULT_CLASS_ICON_ID];
  }
  return CLASS_ICON_MAP[iconId as ClassIconId];
}
